apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service
data:
  DB_NAME: 
  DB_USERNAME: postgres
  DB_HOST: postgres
  DB_PORT: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-service
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=